### 1. test the basic endpoint
POST http://localhost:6060/auth/addUser
content-type: application/json

{
    "full_name":"leader tester",
    "email":"leader@gmail.com",
    "password":"password1",
    "role":2
}
